// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="PostExecuteTemplateRequest.cs">
//   Copyright (c) 2018 Aspose.Words for Cloud
// </copyright>
// <summary>
//   Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
// 
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace Aspose.Words.Cloud.Sdk.Model.Requests 
{
  using Aspose.Words.Cloud.Sdk.Model; 

  /// <summary>
  /// Request model for <see cref="Aspose.Words.Cloud.Sdk.Api.WordsApi.PostExecuteTemplate" /> operation.
  /// </summary>  
  public class PostExecuteTemplateRequest : ICanModifyDocumentRequest, IWordDocumentRequest, ICanSpecifyMailMergeParametersRequest   
  {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostExecuteTemplateRequest"/> class.
        /// </summary>        
        public PostExecuteTemplateRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PostExecuteTemplateRequest"/> class.
        /// </summary>
        /// <param name="data">Mail merge data</param>
        /// <param name="name">The template document name.</param>
        /// <param name="cleanup">Clean up options.</param>
        /// <param name="destFileName">Result name of the document after the operation. If this parameter is omitted then result of the operation will be saved with autogenerated name.</param>
        /// <param name="folder">Original document folder.</param>
        /// <param name="loadEncoding">Encoding that will be used to load an HTML (or TXT) document if the encoding is not specified in HTML.</param>
        /// <param name="password">Password for opening an encrypted document.</param>
        /// <param name="storage">File storage, which have to be used.</param>
        /// <param name="useWholeParagraphAsRegion">Gets or sets a value indicating whether paragraph with TableStart or  TableEnd field should be fully included into mail merge region or particular range between TableStart and TableEnd fields.   The default value is true.</param>
        /// <param name="withRegions">Merge with regions or not. True by default</param>
        public PostExecuteTemplateRequest(string data, string name, string cleanup = null, string destFileName = null, string folder = null, string loadEncoding = null, string password = null, string storage = null, bool? useWholeParagraphAsRegion = null, bool? withRegions = null)             
        {
            this.Data = data;
            this.Name = name;
            this.Cleanup = cleanup;
            this.DestFileName = destFileName;
            this.Folder = folder;
            this.LoadEncoding = loadEncoding;
            this.Password = password;
            this.Storage = storage;
            this.UseWholeParagraphAsRegion = useWholeParagraphAsRegion;
            this.WithRegions = withRegions;
        }

        /// <summary>
        /// Mail merge data
        /// </summary>  
        public string Data { get; set; }

        /// <summary>
        /// The template document name.
        /// </summary>  
        public string Name { get; set; }

        /// <summary>
        /// Clean up options.
        /// </summary>  
        public string Cleanup { get; set; }

        /// <summary>
        /// Result name of the document after the operation. If this parameter is omitted then result of the operation will be saved with autogenerated name.
        /// </summary>  
        public string DestFileName { get; set; }

        /// <summary>
        /// Original document folder.
        /// </summary>  
        public string Folder { get; set; }

        /// <summary>
        /// Encoding that will be used to load an HTML (or TXT) document if the encoding is not specified in HTML.
        /// </summary>  
        public string LoadEncoding { get; set; }

        /// <summary>
        /// Password for opening an encrypted document.
        /// </summary>  
        public string Password { get; set; }

        /// <summary>
        /// File storage, which have to be used.
        /// </summary>  
        public string Storage { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether paragraph with TableStart or  TableEnd field should be fully included into mail merge region or particular range between TableStart and TableEnd fields.   The default value is true.
        /// </summary>  
        public bool? UseWholeParagraphAsRegion { get; set; }

        /// <summary>
        /// Merge with regions or not. True by default
        /// </summary>  
        public bool? WithRegions { get; set; }
  }
}